#!/usr/bin/env python3
"""Task 2 - Equal-weight portfolio baselines ($0).

For each of the five rule-based agents (buy_and_hold, macd, sma_crossover,
momentum, random) and each regime, forms a naive equal-weight (1/N) portfolio
across the five tickers: the EW return is the mean of the per-ticker total
returns. No LLM is included (see the table note).

The four deterministic agents are simulated here with warm indicators and no
look-ahead. The random agent's per-cell value is the N=100 mean produced by
Task 1 (scripts/run_random_n100.py), i.e. the expected uninformed return,
which is far more stable than any single seed.

Zero cost: prices from yfinance (cached by Task 1); pure Python; no API calls.

Outputs
    benchmark/results/baselines/per_cell_returns.csv   (agent, regime, ticker)
    benchmark/results/baselines/ew_returns.csv         (agent, regime)
    docs/paper_ew_portfolio_baselines.tex              (LaTeX table + note)

Usage
    .venv/bin/python scripts/run_ew_portfolio.py   # run Task 1 first
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import regime_lib as rl  # noqa: E402
from tradingagents.backtest.baselines import (  # noqa: E402
    BuyAndHold, MACDStrategy, SMACrossStrategy, MomentumStrategy,
)

BASE_DIR = rl.REPO / "benchmark" / "results" / "baselines"
PERCELL_CSV = BASE_DIR / "per_cell_returns.csv"
EW_CSV = BASE_DIR / "ew_returns.csv"
TEX_PATH = rl.REPO / "docs" / "paper_ew_portfolio_baselines.tex"
RANDOM_SUMMARY = rl.REPO / "benchmark" / "results" / "random_n100" / "summary.csv"

# agent key -> (display name, deterministic strategy)
DETERMINISTIC = {
    "buy_and_hold":  ("Buy \\& Hold",     BuyAndHold()),
    "macd":          ("MACD(12,26,9)",    MACDStrategy()),
    "sma_crossover": ("SMA(50/200)",      SMACrossStrategy()),
    "momentum":      ("Momentum(60)",     MomentumStrategy()),
}
RANDOM_DISPLAY = "Random ($N{=}100$ mean)"
AGENT_ORDER = ["buy_and_hold", "macd", "sma_crossover", "momentum", "random"]
DISPLAY_NAME = {k: v[0] for k, v in DETERMINISTIC.items()} | {"random": RANDOM_DISPLAY}


def load_random_means() -> dict[tuple[str, str], float]:
    """(regime, ticker) -> N=100 mean total return (%), from Task 1."""
    if not RANDOM_SUMMARY.exists():
        raise SystemExit(
            f"Missing {RANDOM_SUMMARY}. Run scripts/run_random_n100.py first.")
    s = pd.read_csv(RANDOM_SUMMARY)
    return {(r.regime, r.ticker): float(r.mean_return_pct) for r in s.itertuples()}


def compute() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Return (per_cell_df, ew_df) with returns in percent."""
    random_means = load_random_means()

    # Deterministic strategies need the price frames; cache in memory.
    price = {t: rl.load_prices(t) for t in rl.TICKERS}

    percell_rows: list[dict] = []
    for agent in AGENT_ORDER:
        for regime in rl.REGIME_ORDER:
            for ticker in rl.TICKERS:
                if agent == "random":
                    ret_pct = random_means[(regime, ticker)]
                else:
                    _, strat = DETERMINISTIC[agent]
                    ret_pct = rl.run_strategy_cell(strat, price[ticker], regime) * 100.0
                percell_rows.append({
                    "agent": agent, "regime": regime, "ticker": ticker,
                    "total_return_pct": round(ret_pct, 4),
                })

    percell = pd.DataFrame(percell_rows)

    ew_rows: list[dict] = []
    for agent in AGENT_ORDER:
        for regime in rl.REGIME_ORDER:
            sub = percell[(percell.agent == agent) & (percell.regime == regime)]
            ew_rows.append({
                "agent": agent, "regime": regime,
                "ew_return_pct": round(float(sub["total_return_pct"].mean()), 4),
                "n_tickers": len(sub),
            })
    ew = pd.DataFrame(ew_rows)
    return percell, ew


def write_tex(ew: pd.DataFrame, path: Path) -> None:
    """5 agents (rows) x 4 regimes (cols), EW return in percent."""
    regimes = rl.REGIME_ORDER
    reg_hdr = " & ".join(r.replace("_", r"\_") for r in regimes)

    lines: list[str] = []
    lines.append("% Auto-generated by scripts/run_ew_portfolio.py -- do not edit by hand.")
    lines.append("% Requires: \\usepackage{booktabs}")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{l" + "r" * len(regimes) + "}")
    lines.append("\\toprule")
    lines.append(f"Agent (EW, \\%) & {reg_hdr} \\\\")
    lines.append("\\midrule")
    for agent in AGENT_ORDER:
        cells = []
        for regime in regimes:
            v = ew[(ew.agent == agent) & (ew.regime == regime)]["ew_return_pct"].iloc[0]
            cells.append(f"{v:.1f}")
        lines.append(f"{DISPLAY_NAME[agent]} & " + " & ".join(cells) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")

    caption = (
        "\\caption{\\textbf{Equal-weight portfolio returns by rule-based agent "
        "and regime.} Each entry is the naive equal-weight (1/5) portfolio total "
        "return across the five tickers (PETR4, VALE3, ITUB4, BBDC4, "
        "\\texttt{\\^{}BVSP}), i.e.\\ the mean of the per-ticker cumulative "
        "returns, over the four dated regime windows. All strategies are "
        "long-only, binary (all-in/all-cash), and frictionless; the trend "
        "strategies (MACD, SMA, Momentum) use a pre-window warmup buffer so "
        "their indicators are warm at each window's first bar (no look-ahead). "
        "The Random row is the $N{=}100$-seed mean per ticker from "
        "Table~\\ref{tab:random-n100}, i.e.\\ the expected uninformed return "
        "rather than a single noisy seed. "
        "\\emph{LLM excluded: sequential multi-seed evaluation prevents proper "
        "simultaneous portfolio construction.} These are classical baselines "
        "only; the multi-agent LLM pipeline is evaluated separately.}"
    )
    lines.append(caption)
    lines.append("\\label{tab:ew-baselines}")
    lines.append("\\end{table}")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def main() -> int:
    BASE_DIR.mkdir(parents=True, exist_ok=True)
    percell, ew = compute()

    percell.to_csv(PERCELL_CSV, index=False)
    ew.to_csv(EW_CSV, index=False)
    write_tex(ew, TEX_PATH)

    # Console: agents (rows) x regimes (cols).
    print("Equal-weight portfolio return (%) -- rule-based agents only, LLM excluded\n")
    pivot = ew.pivot(index="agent", columns="regime", values="ew_return_pct")
    pivot = pivot.reindex(index=AGENT_ORDER, columns=rl.REGIME_ORDER)
    print(pivot.to_string(float_format=lambda x: f"{x:7.2f}"))
    print(f"\nWrote:\n  {PERCELL_CSV}\n  {EW_CSV}\n  {TEX_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
