#!/usr/bin/env python3
"""Task 1 - RandomAgent, N=100 seeds ($0, CPU only).

Runs an uninformed RandomAgent (i.i.d. uniform BUY/SELL/HOLD per day) with
seeds 0..99 over the study grid of 5 tickers x 4 regimes (20 cells). For each
cell it summarises the distribution of total return across seeds and locates
the canonical seed=42 draw within that distribution.

Zero cost: prices are pulled from yfinance (free) and cached; no LLM calls.

Outputs
    benchmark/results/random_n100/summary.csv        (one row per cell)
    benchmark/results/random_n100/per_seed_returns.csv (long, 20*100 rows)
    docs/paper_random_n100.tex                        (LaTeX table + caption)

Usage
    .venv/bin/python scripts/run_random_n100.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import regime_lib as rl  # noqa: E402

OUT_DIR = rl.REPO / "benchmark" / "results" / "random_n100"
SUMMARY_CSV = OUT_DIR / "summary.csv"
PERSEED_CSV = OUT_DIR / "per_seed_returns.csv"
TEX_PATH = rl.REPO / "docs" / "paper_random_n100.tex"

SEEDS = list(range(rl.N_SEEDS))  # 0..99, includes seed 42

# Pretty labels for the index ticker in LaTeX (^ is a reserved char).
DISPLAY = {"^BVSP": "IBOV"}


def display_ticker(t: str) -> str:
    return DISPLAY.get(t, t)


def compute() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Run the full grid and return (summary_df, per_seed_df)."""
    summary_rows: list[dict] = []
    perseed_rows: list[dict] = []

    for ticker in rl.TICKERS:
        df = rl.load_prices(ticker)
        for regime in rl.REGIME_ORDER:
            win = rl.regime_window(df, regime)
            n_days = len(win)
            returns = np.array(
                [rl.run_random_cell(df, regime, s) for s in SEEDS], dtype=float
            )
            for s, r in zip(SEEDS, returns):
                perseed_rows.append(
                    {"regime": regime, "ticker": ticker, "seed": s,
                     "total_return_pct": round(r * 100.0, 6)}
                )

            seed42 = float(returns[rl.SEED42])
            pctile = rl.percentile_of(returns, seed42)
            summary_rows.append({
                "regime": regime,
                "ticker": ticker,
                "n_days": n_days,
                "n_seeds": len(SEEDS),
                "mean_return_pct": returns.mean() * 100.0,
                "std_return_pct": returns.std(ddof=1) * 100.0,
                "p5_return_pct": np.percentile(returns, 5) * 100.0,
                "p95_return_pct": np.percentile(returns, 95) * 100.0,
                "min_return_pct": returns.min() * 100.0,
                "max_return_pct": returns.max() * 100.0,
                "seed42_return_pct": seed42 * 100.0,
                "seed42_percentile": pctile,
            })
            print(f"  {regime:14s} {ticker:6s} "
                  f"mean={returns.mean()*100:7.2f}%  sd={returns.std(ddof=1)*100:6.2f}  "
                  f"[p5={np.percentile(returns,5)*100:7.2f}, p95={np.percentile(returns,95)*100:7.2f}]  "
                  f"seed42={seed42*100:7.2f}% @ {pctile:4.1f} pctile")

    summary = pd.DataFrame(summary_rows)
    perseed = pd.DataFrame(perseed_rows)
    return summary, perseed


def _fnum(x: float, d: int = 1) -> str:
    return f"{x:.{d}f}"


def write_tex(summary: pd.DataFrame, path: Path) -> None:
    """Emit a booktabs LaTeX table (20 cells, grouped by regime) + caption."""
    # Aggregate facts for an honest, data-driven caption.
    pcts = summary["seed42_percentile"].to_numpy()
    n_cells = len(summary)
    n_extreme = int(np.sum((pcts < 5) | (pcts > 95)))
    med_pctile = float(np.median(pcts))
    mean_pctile = float(np.mean(pcts))

    regime_esc = {r: r.replace("_", r"\_") for r in rl.REGIME_ORDER}

    lines: list[str] = []
    lines.append("% Auto-generated by scripts/run_random_n100.py -- do not edit by hand.")
    lines.append("% Requires: \\usepackage{booktabs}, \\usepackage{multirow}")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{llrrrrr}")
    lines.append("\\toprule")
    lines.append("Regime & Ticker & Mean$\\pm$SD (\\%) & P5 (\\%) & P95 (\\%) "
                 "& seed42 (\\%) & seed42 pctile \\\\")
    lines.append("\\midrule")

    for ri, regime in enumerate(rl.REGIME_ORDER):
        sub = summary[summary["regime"] == regime].reset_index(drop=True)
        for j, row in sub.iterrows():
            if j == 0:
                regcell = f"\\multirow{{{len(sub)}}}{{*}}{{{regime_esc[regime]}}}"
            else:
                regcell = ""
            mean_sd = f"{_fnum(row['mean_return_pct'])}$\\pm${_fnum(row['std_return_pct'])}"
            lines.append(
                f"{regcell} & {display_ticker(row['ticker'])} & {mean_sd} & "
                f"{_fnum(row['p5_return_pct'])} & {_fnum(row['p95_return_pct'])} & "
                f"{_fnum(row['seed42_return_pct'])} & {_fnum(row['seed42_percentile'])} \\\\"
            )
        if ri < len(rl.REGIME_ORDER) - 1:
            lines.append("\\midrule")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")

    caption = (
        "\\caption{\\textbf{RandomAgent null distribution, $N=100$ seeds.} "
        "Each cell reports the distribution of total return (cumulative return, "
        "CR) of an uninformed RandomAgent that draws BUY/SELL/HOLD i.i.d.\\ "
        "uniformly each trading day, evaluated with the same frictionless, "
        "long-only, all-in/all-cash execution as the paper's baselines, over "
        "seeds $0$--$99$. Mean$\\pm$SD, the 5th/95th percentiles, and the "
        "canonical seed=42 draw are shown per (regime, ticker) cell; "
        "\\emph{seed42 pctile} is the percentile rank of the seed=42 return "
        "within that cell's 100-seed distribution. IBOV denotes the Ibovespa "
        "index (\\texttt{\\^{}BVSP}). "
        f"Across the {n_cells} cells, the seed=42 draw sits at a median "
        f"percentile of {_fnum(med_pctile)} (mean {_fnum(mean_pctile)}); it "
        f"falls in a distribution tail ($<$5th or $>$95th pctile) in "
        f"{n_extreme} of {n_cells} cells. "
        "This quantifies the dispersion of an uninformed policy, not skill: "
        "the wide spreads---largest in the high-volatility \\texttt{crisis\\_2020} "
        "window---reflect the path dependence of random entry/exit timing. A "
        "single fixed seed is therefore a noisy point estimate of random-agent "
        "performance, which is why downstream portfolio comparisons average "
        "over all 100 seeds.}"
    )
    lines.append(caption)
    lines.append("\\label{tab:random-n100}")
    lines.append("\\end{table}")
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def main() -> int:
    print(f"RandomAgent N={rl.N_SEEDS} over {len(rl.TICKERS)} tickers x "
          f"{len(rl.REGIME_ORDER)} regimes = {len(rl.TICKERS)*len(rl.REGIME_ORDER)} cells")
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    summary, perseed = compute()

    # Round summary for storage (keep percentile at 2 dp, returns at 4 dp).
    store = summary.copy()
    ret_cols = [c for c in store.columns if c.endswith("_return_pct")]
    store[ret_cols] = store[ret_cols].round(4)
    store["seed42_percentile"] = store["seed42_percentile"].round(2)
    store.to_csv(SUMMARY_CSV, index=False)
    perseed.to_csv(PERSEED_CSV, index=False)
    write_tex(summary, TEX_PATH)

    # Seed-42 representativeness verdict (console).
    pcts = summary["seed42_percentile"].to_numpy()
    n_extreme = int(np.sum((pcts < 5) | (pcts > 95)))
    print("\n" + "=" * 64)
    print("SEED=42 vs the N=100 distribution")
    print(f"  median percentile = {np.median(pcts):.1f}  (50 = perfectly typical)")
    print(f"  mean   percentile = {np.mean(pcts):.1f}")
    print(f"  in a tail (<5 or >95 pctile): {n_extreme}/{len(pcts)} cells")
    if n_extreme <= 2:
        print("  -> seed=42 is broadly REPRESENTATIVE (rarely an outlier).")
    else:
        print(f"  -> seed=42 is an OUTLIER in {n_extreme} cells; treat single-seed"
              " random results with caution.")
    print("=" * 64)
    print(f"\nWrote:\n  {SUMMARY_CSV}\n  {PERSEED_CSV}\n  {TEX_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
